<style>

            h4
            {
                font-weight: bold;
                margin: 10px 0px;
            }
            
            h4.divider
            {
                color: #D44A44;
                font-size: 12px;
            }

            h5
            {
                font-size: 11px;
                margin: 10px 0px;
            }

            .numberInput
            {
                width: 50px;
            }

            textarea
            {
                width: 100%;
            }
            
            table
            {
                width: 98%;
                border-left: 4px solid #7AD03A;
                padding-left: 2%;
                box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.1);
                background: white;
                padding-bottom: 15px;
            }
            
            table.inner-table
            {
                border: 0px;
                box-shadow: none;
            }

            table td
            {
                width: 48%;
                padding-right: 2%;
                vertical-align: top;
            }
            
            .default
            {
                font-size: 8px;
                font-style: italic;
            }

            .error
            {
                color: red;
            }
            
            .success
            {
                color: green;
            }

            #RMVersion
            {
                float: right;
                border-left: 4px solid #7AD03A;
                padding: 10px;
                background: white;
                box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.1);
            }
            
            #RMVersion.beta
            {
                border-color: orange;
            }
            
            .note
            {
                padding: 25px 0px 0px 0px;
                color: green;
            }
            
            .button.file
            {
                background: white;
                padding: 0px !important;
            }
            
            @media only screen and ( min-width : 0px ) and ( max-width : 600px ) { 

                table, table td, table tr
                {
                    width: 100%;
                    display: block;
                }
                
            }
            
        </style>

        <div class="wrap">

            <div id="RMVersion" <?php echo NI_Mailchimp_Registry::get( 'config', 'is_beta' ) ? 'class="beta"' : ''; ?>>
                <?php _e( 'Version', 'ni-mailchimp' ); ?> <?php echo NI_Mailchimp_Registry::get( 'config', 'current_version' ); ?> 
                <?php echo NI_Mailchimp_Registry::get( 'config', 'is_beta' ) ? 'Beta' : ''; ?>
                
            </div>
          
            <form action="" method="post">

                <h2><?php _e( 'NI Mailchimp Options', 'ni-mailchimp' ); ?></h2>

                <?php if ( $status = NI_Mailchimp_Status::get() )
                    echo self::statusBar( $status ); ?>
                
                <table>

                <h3><?php _e( 'API Details', 'ni-mailchimp' ); ?></h3>
                 
                <table>
                    
                    <tr>
                        <td>
                            
                            <h4><?php _e( 'API Key', 'ni-mailchimp' ); ?></h4> 

                            <h5><?php _e( 'This is the API key which can be found from', 'ni-mailchimp' ); ?></h5>

                            <input 
                                type="text" 
                                name="ApiKey" 
                                value="<?php echo isset( $data['ApiKey'] ) ? $data['ApiKey'] : ''; ?>" 
                                />
                            
                        </td>
                        <td>

                            <h4><?php _e( 'List ID', 'ni-mailchimp' ); ?></h4> 

                            <h5><?php _e( 'This is the list ID which can be found from', 'ni-mailchimp' ); ?></h5>

                            <input 
                                type="text" 
                                id="ListId" 
                                name="ListId" 
                                value="<?php echo isset( $data['ListId'] ) ? $data['ListId'] : ''; ?>" 
                                />

                        </td>
                    </tr>
                    <tr>
                        <td>
                            
                            <h4><?php _e( 'Sign up button text', 'ni-mailchimp' ); ?></h4> 

                            <h5><?php _e( 'This is the text found on the submit button itself', 'ni-mailchimp' ); ?></h5>

                            <input 
                                type="text" 
                                name="SbtBtnTxt" 
                                value="<?php echo isset( $data['SbtBtnTxt'] ) ? $data['SbtBtnTxt'] : ''; ?>" 
                                />
                            
                        </td>
                        <td>

                            <h4><?php _e( 'Email placeholder text', 'ni-mailchimp' ); ?></h4> 

                            <h5><?php _e( 'This is the semi transparent placeholder text found on the email signup bar', 'ni-mailchimp' ); ?></h5>

                            <input 
                                type="text" 
                                id="EPlcHol" 
                                name="EPlcHol" 
                                value="<?php echo isset( $data['EPlcHol'] ) ? $data['EPlcHol'] : ''; ?>" 
                                />

                        </td>
                    </tr>
                                    
                </table>
                
                <br /><br />

                <input 
                    type="submit" 
                    class="button button-primary" 
                    name="NI_Mailchimp_Submit" 
                    value="<?php _e( 'Update NI Mailchimp Options', 'ni-mailchimp' ); ?>"
                    />

            </form>

        </div>